#!/bin/sh -eux

ub_install
sed s%freetype/config%freetype2/freetype/config% -i $UB_INSTALLDIR/usr/include/freetype2/ft2build.h
cd ft2demos
	cp bin/.libs/ft* ${UB_INSTALLDIR}/usr/bin
cd ..

cp builds/unix/freetype-config ${UB_INSTALLDIR}/usr/bin/
