#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/share/{applications,icons,metainfo,mime}
mv usr/share/icons ${UB_INSTALLDIR}/usr/share/
mv usr/share/metainfo ${UB_INSTALLDIR}/usr/share/
mv usr/share/mime ${UB_INSTALLDIR}/usr/share/
mv opt lib
mv lib/libreoffice* lib/libreoffice-bin

# nem kell java
rm lib/libreoffice-bin/program/libofficebean.so

# desktopok
cd lib/libreoffice-bin/share/xdg
patch -i ${UB_SRCDIR}/patches/desktops.patch.skip
cd -
cp lib/libreoffice-bin/share/xdg/*.desktop $UB_INSTALLDIR/usr/share/applications/

mv lib/* $UB_INSTALLDIR/usr/lib/
ln -s /usr/lib/libreoffice-bin/program/soffice ${UB_INSTALLDIR}/usr/bin/libreoffice-bin
