#!/bin/sh -eux

autoreconf -vif
export CXXFLAGS+=' -Wno-deprecated-declarations '
ub_compile \
	--enable-xft \
	--enable-xrender \
	--enable-xpm \
	--enable-imlib2 \
	--enable-xinerama \
	--enable-xrandr \
	--enable-fribidi
