#!/bin/sh -eux

ub_install

cp ${UB_SRCDIR}/sources/Doom-1-icon.png "$UB_INSTALLDIR"/usr/share/pixmaps/gzdoom.png
mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/256x256/apps
cp src/posix/zdoom.xpm ${UB_INSTALLDIR}/usr/share/icons/hicolor/256x256/apps/gzdoom.xpm
