#!/bin/sh -eux

cd googletest
sed -r "s|(Version:) .+|\1 ${UB_VERSION}|" -i gtest.pc.in
export CXXFLAGS+=' -Wno-dangling-else -Wno-parentheses -Wno-deprecated-copy '
ub_compile \
    -DBUILD_GMOCK=ON \
    -DBUILD_GTEST=ON \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_SKIP_BUILD_RPATH=TRUE \
	-DPYTHON_EXECUTABLE=/usr/bin/python3 \
	-Dgmock_build_tests=ON \
	-Dgtest_build_tests=ON \
	-Dgtest_build_sampless=OFF \
	-Dgtest_disable_pthreads=OFF

cd ../googlemock
ub_compile \
    -DBUILD_SHARED_LIBS=ON
