#!/bin/sh -eux

if [ ! -f version ]; then
	echo "echo $UB_VERSION" > version
fi

# NOCONFIGURE=1 ./autogen.sh

ub_compile \
    --enable-enchant \
    --enable-crash-dialog \
    --enable-ldap \
    --enable-pgpmime-plugin \
    --enable-spamassassin-plugin \
    --enable-bogofilter-plugin \
    --enable-fancy-plugin \
    --enable-pgpmime-plugin \
    --enable-manual \
    --disable-alternate-addressbook \
    --disable-bsfilter-plugin \
    --disable-python-plugin
# ub_make -C po claws-mail.pot update-po
