#!/bin/sh -eux

sed -i "1s/python$/&2/" bin/make_manual.py bin/make_backend_docs.py
export GOFLAGS="-buildmode=pie -trimpath"
PATH="/build/go/bin:$PATH" make TAG=v$UB_VERSION rclone rclone.1 || true
PATH="/build/go/bin:$PATH" ./rclone genautocomplete bash rclone.bash_completion
PATH="/build/go/bin:$PATH" ./rclone genautocomplete zsh rclone.zsh_completion
