#!/bin/sh -eux

autoreconf -vif
export CFLAGS+='-Wno-unused-variable -Wno-pointer-to-int-cast -Wno-uninitialized '
export CFLAGS+='-Wno-parentheses -Wno-int-to-pointer-cast -Wno-deprecated-declarations '
export CFLAGS+='-Wno-incompatible-pointer-types -Wno-unused-function '
export CFLAGS+='-Wno-return-type -Wno-unused-but-set-variable -Wno-implicit-function-declaration'
ub_compile
