#!/bin/sh -eux

ub_install \
	UPDATE_ICON_CACHE=true

mkdir -p "$UB_INSTALLDIR"/usr/share/gtkdialog
cp -a examples/. "$UB_INSTALLDIR"/usr/share/gtkdialog/
#mv ${UB_INSTALLDIR}/usr/bin/gtkdialog ${UB_INSTALLDIR}/usr/bin/gtkdialog.bin
