#!/bin/sh -eux

ub_install

mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor
cp -a build/share ${UB_INSTALLDIR}/usr/
cp -a data/icons/* ${UB_INSTALLDIR}/usr/share/icons/hicolor/
rm $UB_INSTALLDIR/usr/bin/gufw
mv $UB_INSTALLDIR/usr/bin/gufw-pkexec $UB_INSTALLDIR/usr/bin/gufw
