#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a ttf/batang.ttf "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a ttf/dotum.ttf "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a ttf/gulim.ttf "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a ttf/hline.ttf "$UB_INSTALLDIR/usr/share/fonts/truetype"
