#!/bin/sh -eux

autoreconf -vif
export UB_MAKE_PROCS=1
ub_compile \
	--disable-local \
	--disable-tests \
	--enable-aptcc \
	--disable-cron \
	--enable-introspection \
	--enable-gtk-module \
	--enable-gstreamer-plugin \
	--disable-gtk-doc \
	--disable-systemd
