#!/bin/sh -eux

export CTARGET="x86_64-linux-gnu"
export CHOST="x86_64-linux-gnu"
export CBUILD="x86_64-linux-gnu"

sed -i -e "/--build/d" libraries/source/spidermonkey/build.sh

export CXXFLAGS+=' -DU_USING_ICU_NAMESPACE=1 -Wno-deprecated-copy '
export CXXFLAGS+=' -Wno-class-memaccess -Wno-unused-but-set-variable -DBOOST_BIND_GLOBAL_PLACEHOLDERS '

export SDL2_CONFIG="pkg-config sdl2"
cd build/workspaces
./update-workspaces.sh \
	--bindir=/usr/bin \
    --libdir=/usr/lib/0ad \
    --datadir=/usr/share/0ad/data \
    --without-pch \
    --without-tests \
    --without-nvtt
cd gcc
ub_make
