#!/bin/sh -eux

export CTARGET="x86_64-linux-gnu"
export CHOST="x86_64-linux-gnu"
export CBUILD="x86_64-linux-gnu"

cd build/workspaces
export CXXFLAGS+=' -DU_USING_ICU_NAMESPACE=1 -Wno-deprecated-copy -Wimplicit-fallthrough=0 -Wno-class-memaccess '
export CXXFLAGS+=' -Wno-cpp -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-uninitialized'
export SDL2_CONFIG="pkg-config sdl2"
export PYTHON=python2
./update-workspaces.sh \
	--bindir=/usr/bin \
    --libdir=/usr/lib/0ad \
    --datadir=/usr/share/0ad/data \
    --without-pch \

cd gcc
ub_make
