#!/bin/sh -eux

mv dist/*.whl installer.zip
pythonver=$(python3 -V | sed 's/Python /python/' | sed s/\..$//)
sitedir=${UB_INSTALLDIR}/usr/lib/${pythonver}/site-packages
mkdir -p $sitedir
unzip installer -d $sitedir/
