#!/bin/sh -eux

pkgid=$(cat $UB_SRCDIR/sourcename)
compiler=$(ls -d /usr/lib/ghc* | sed s%.*/%%)
gen-setup
runhaskell Setup configure -O --enable-shared --enable-executable-dynamic --disable-library-vanilla \
    --prefix=/usr --docdir=/usr/share/doc/Packages/$pkgid \
    --dynlibdir=/usr/lib --libsubdir=\$compiler/site-local/\$pkgid
runhaskell Setup build
runhaskell Setup register --gen-script
runhaskell Setup unregister --gen-script
sed /PATH/d -i register.sh
sed /PATH/d -i unregister.sh
